### ISSUE TITLE
directory reorder

### ISSUE THREAD

**Issue by Recogn1z** [sonnyding1/sticker-stride#3]

**Comment by sonnyding1** [comment]
Did you mean, "create a new folder 'components' to store components"? Also, should I make the calendar into a component?

**Comment by sonnyding1** [comment]
Also I think you meant "directory", not "direction", which means folder. You meant "component folder", not "component list".

**Comment by Recogn1z** [comment]
create component folder to store all components will be used in the future(calender, navigation, etc..)
